Add scatter functionality for loops
caracal-pipeline/stimela pull request #10
Opened 2022-02-02 15:28 UTC by SpheMakh

- Add pathos and dill as deps
-  set `skip_implicits = False` by default for parameters
- Add `for_loop.scatter` functionality

2022-02-13 15:10 UTC, o-smirnov requested changes

2022-02-13 15:10 UTC, o-smirnov commented on setup.py
> +<<<<<<< HEAD
Looks like an unresolved merge.

2022-02-13 15:10 UTC, o-smirnov commented on stimela/__init__.py
> +from stimela.kitchen.recipe import PyRecipe as Recipe
Thought we're going to retire PyRecipe?

2022-02-13 15:10 UTC, o-smirnov commented on stimela/commands/exxec.py
> +    Execute a single cab, or a recipe from a YML file_pickle.PicklingError: Can't pickle <class 'types.UpdatedStimelaConfig'>: it's not found as types.UpdatedStimelaConfig.
Ooops where did the error come from? Wild paste?

2022-02-15 11:13 UTC, sphemakh commented on stimela/__init__.py
> +from stimela.kitchen.recipe import PyRecipe as Recipe
fixed

2022-02-15 11:14 UTC, SpheMakh commented on setup.py
> +<<<<<<< HEAD
We can put a pypi dep before we release. But this is OK for now since using a release that doesn't exist breaks the install

2022-02-15 14:24 UTC, o-smirnov approved these changes

2022-02-15 14:24 UTC, merged