fixes #126. Fixes #129. Fixes #130. Fixes #125. Fixed #116.
caracal-pipeline/stimela pull request #131
Opened 2023-01-12 09:47 UTC by o-smirnov

Initial steps towards #127 and #128, too.

2023-01-13 13:46 UTC, SpheMakh requested changes

2023-01-13 13:46 UTC, SpheMakh commented on stimela/commands/run.py
>      return 0
Please add newline

2023-01-13 13:56 UTC, o-smirnov commented on stimela/commands/run.py
>      return 0
Done.

2023-02-03 13:27 UTC, SpheMakh approved these changes

2023-02-03 13:28 UTC, merged