Singularize!
caracal-pipeline/stimela pull request #154
Opened 2023-04-12 10:23 UTC by o-smirnov

OK I have most of a real-life recipe running with singularity containers, so in the interest of release early, release often, let's push this out.

I'll open a cult-cargo PR to accompany this shortly.

Putting this at the start of a recipe enables the singularity backend. I haven't yet updated the click options to set this from the command line, but we should.

```yml
opts:
  backend:
    singularity:
      enable: true
      auto_update: true
```

2023-04-24 08:27 UTC, SpheMakh requested changes

2023-04-24 08:27 UTC, SpheMakh commented on stimela/backends/__init__.py
> +
Why leave this commented-out code here?

2023-04-24 08:27 UTC, SpheMakh commented on stimela/backends/__init__.py
> +    # name: str = MISSING
ditto

2023-04-24 08:27 UTC, sphemakh commented on stimela/backends/kubernetes/__init__.py
> +import json, yaml
one import per line

2023-04-24 08:27 UTC, SpheMakh commented on stimela/backends/kubernetes/run_kube.py
>  import logging, time, json, datetime, yaml, os.path, uuid, pathlib
One import per line

2023-04-24 08:27 UTC, SpheMakh commented on stimela/backends/native/__init__.py
> +from .run_native import run, build_command_line, update_rlimits
add new line at end file

2023-04-24 08:27 UTC, sphemakh commented on stimela/config.py
> +    ## replaced by cult-cargo
remove old code, don't comment it out

2023-04-24 08:27 UTC, sphemakh commented on stimela/config.py
> +        # dependencies.replace((base_configs_glob, cab_configs_glob, lib_configs_glob), STIMELA_DIR)
remove

2023-04-24 08:27 UTC, sphemakh commented on stimela/kitchen/step.py
ditto for old code

2023-04-24 08:27 UTC, SpheMakh commented on stimela/main.py
> +# @click.option('--backend', '-b', type=click.Choice(config.Backend._member_names_),
ditoo for old code

2023-04-24 08:27 UTC, SpheMakh commented on stimela/main.py
> +    # # print backends
Ditto

2023-04-24 08:27 UTC, sphemakh commented on stimela/stimela.conf
> +    default-casa: quay.io/stimela2/casa:cc0.0.2
add new line

2023-04-24 08:29 UTC, SpheMakh commented
Run auto [pep8](https://pypi.org/project/autopep8) and re-commit

2023-05-05 19:01 UTC, o-smirnov commented on stimela/main.py
> +# @click.option('--backend', '-b', type=click.Choice(config.Backend._member_names_),
Reenabled option.

2023-05-05 19:06 UTC, o-smirnov commented on stimela/backends/kubernetes/__init__.py
> +import json, yaml
Let's not be PEP-8 nazis, nothing wrong with compounding standard library imports when there's many to be done.

2023-05-05 19:07 UTC, o-smirnov commented on stimela/backends/kubernetes/run_kube.py
>  import logging, time, json, datetime, yaml, os.path, uuid, pathlib
See above.

2023-05-05 19:11 UTC, o-smirnov commented
@SpheMakh recheck please. Along with https://github.com/caracal-pipeline/cult-cargo/pull/3

2023-05-16 12:07 UTC, SpheMakh approved these changes

2023-05-16 12:07 UTC, merged