Honour always tag even when step selection is in use.
caracal-pipeline/stimela pull request #272
Opened 2024-04-09 13:10 UTC by JSKenyon

Currently, invoking `stimela run recipe.yml -s dependent_step` will fail if `dependent_step` depends on the outputs of a preceding step. The user can specify `stimela run recipe.yml -s dependency_step -s dependent_step`, but this can become tedious and may require more in-depth recipe knowledge. The natural mechanism for handling this case is the `always` tag i.e. steps tagged as `always` are integral to recipe functionality and as such should always be run. Currently, `-s` will completely ignore any tags. This PR instead augments the selected steps with the `always` steps. One downside of this approach is that the `always` steps may be run even when they are unnecessary i.e. if a users only runs steps prior to the always step, they cannot be a requirement. @o-smirnov thoughts?

2024-04-09 13:14 UTC, JSKenyon commented
My feeling is that `always` should be reserved for steps which can independently of any steps outside the `always` group. An example of this would be the `ms-info` step of the parrot pipeline. It should always be run as it is necessary for other step. The alternative is to support a `step_requires` field but that may become quite involved.

2024-04-09 13:55 UTC, o-smirnov commented
Thanks @JSKenyon I like that idea. Do we need an extra command-line option to explicitly ski (--skip/-k) a step tagged with always?

P.S. I've already been thinking about auto-dependencies for a future version: https://github.com/caracal-pipeline/stimela/discussions/254#discussioncomment-8680734

2024-04-09 14:14 UTC, JSKenyon commented
> Thanks @JSKenyon I like that idea. Do we need an extra command-line option to explicitly skip (--skip/-k) a step tagged with always?

I have added a simple (--skip-step/-k) command for explicitly disabling specific steps. This should also work when you want to skip a step inside a tagged group.

2024-04-09 15:02 UTC, o-smirnov requested changes
Should -k/--skip also not apply inside a range selected with -s FROM:TO?

2024-04-09 15:02 UTC, o-smirnov commented on stimela/commands/run.py
> +                help="""Forcefully skip the spcified step. This is option is primarily for skipping specific steps in
Typo here, "spcified".

2024-04-10 06:38 UTC, JSKenyon commented
I have decided to take a stab at rewriting the `restrict_steps` function. Will resubmit for review when I am done.

2024-04-10 12:02 UTC, JSKenyon commented
@o-smirnov I have rewritten some of the restrict logic and I believe that it is now a little clearer. This probably results in slight changes in behaviour but I think the new approach is more powerful than the old. Specifically, `-t` and `-s` can now be combined e.g. `stimela run recipe.yml -t some_steps -s extra_step`. This will run all the tagged steps in addition to the extra step. Steps tagged as `always` will always run unless explicitly skipped with `-k`. `-k` now supports the same behaviour as `-s` for ranges of steps.  Let me know what you think.

2024-04-16 13:08 UTC, o-smirnov approved these changes
Looks good and is extremely useful, thanks @JSKenyon!

2024-04-16 13:08 UTC, merged