added IS_STR, IS_NUM, VALID to formula language
caracal-pipeline/stimela pull request #342
Opened 2024-10-28 09:29 UTC by o-smirnov

Adding the power spectrum branch to TRON strained at the limits of the parser a little, so I added these functions to make things more tractcable.

2024-10-28 09:38 UTC, JSKenyon requested changes
Just one minor comment about the docs.

2024-10-28 09:38 UTC, JSKenyon commented on docs/source/fundamentals/substitutions.rst
> +  error is ``a`` is a string, but ``VALID(recipe.a > 0)
This documentation looks incomplete/cut off.

2024-10-28 09:40 UTC, JSKenyon commented on scabha/evaluator.py
> +import numpy as np
Numpy needs to be added to to the dependencies - tests currently fail.

2024-10-28 09:59 UTC, JSKenyon submitted a review, later dismissed

2024-10-28 10:00 UTC, JSKenyon commented
3.12 tests are failing due to deprecated functionality. I would personally advocate for evicting 3.8 from the test matrix. It has moved to EOL as of 2024-10-07 (see https://devguide.python.org/versions/).

2024-10-28 10:18 UTC, o-smirnov commented
I'm not particularly attached to 3.8, but how does dropping it help the 3.12 issue?

2024-10-28 11:03 UTC, JSKenyon commented
> I'm not particularly attached to 3.8, but how does dropping it help the 3.12 issue?

Managed to reproduce locally. The poetry installer tries to produce a uniform environment over all the Python versions. That results in an old numpy being installed to satisfy Python 3.8. I have pushed a fix - let us see if it works.

2024-12-11 06:39 UTC, o-smirnov commented
@JSKenyon @SpheMakh please re-review.

2024-12-11 06:41 UTC, JSKenyon approved these changes

2024-12-11 06:43 UTC, merged