Reintegrating scabha, and also #47
caracal-pipeline/stimela pull request #49
Opened 2022-06-28 11:29 UTC by o-smirnov

@SpheMakh don't merge yet. Opening PR so that tests can start running.

2022-06-29 11:21 UTC, SpheMakh requested changes

2022-06-29 11:21 UTC, SpheMakh commented on stimela/commands/clean.py
> +
Let's delete this old code instead of commenting it out

2022-06-29 11:21 UTC, SpheMakh commented on stimela/commands/kill.py
> +    # log = logger.StimelaLogger(LOG_FILE)
ditto

2022-06-29 11:21 UTC, SpheMakh commented on stimela/commands/pull.py
> +    pass
ditto

2022-06-29 11:21 UTC, SpheMakh commented on tests/scabha_tests/test_schema.py
> +    test_schema()
add newline

2022-06-29 11:21 UTC, SpheMakh commented on tests/scabha_tests/test_schema.yaml
> +    default: [1,2]
add newline

2022-06-29 11:21 UTC, SpheMakh commented on tests/scabha_tests/test_substitutions.py
> +    # with substitutions_from(ns) as context:
nuke old code

2022-07-06 10:35 UTC, o-smirnov commented
OK it's all green and I addressed your review. @SpheMakh will you do the merge honours please.

2022-07-08 09:46 UTC, o-smirnov commented
@SpheMakh reminder.

2022-07-29 10:31 UTC, SpheMakh approved these changes

2022-07-29 10:31 UTC, merged