Setup readthedocs
caracal-pipeline/stimela pull request #72
Opened 2022-10-24 13:12 UTC by SpheMakh

2022-10-24 13:15 UTC, sjperkins commented on docs/source/conf.py
> +language = 'ls -lrt'
Maybe should be English?

2022-10-24 13:16 UTC, sjperkins commented on docs/source/conf.py
> +copyright = '2022, Sphesihle Makhathini, Oleg Smirnov and RATT'
If it's convenient, you could import datetime and programmatically generate the year  in an f-string.

2022-10-24 13:23 UTC, sjperkins commented on readthedocs.yaml
> +      - poetry install --with docs
OK this is going to depend on a poetry group called `docs` which isn't present in `pyproject.toml` . You can also read here for more info: https://python-poetry.org/docs/managing-dependencies/#dependency-groups and probably dask-ms's `pyproject.toml` for how to create it.

Groups don't have a `setup.py` correspondence, they're a new poetry feature. There's potential for confusion here.

Note that poetry also has the concept of [extras](https://python-poetry.org/docs/pyproject#extras) which *does* correspond to `setup.py`'s `extras_require` feature

2022-10-24 13:26 UTC, sjperkins commented on docs/source/conf.py
> +html_theme = 'alabaster'
[furo](https://github.com/pradyunsg/furo) is a nice theme but you'll have to add it to the `docs` group mentioned elsewhere in this review.

```suggestion
html_theme = 'furo'
```

I don't think this is critical though.

2022-10-24 13:30 UTC, sjperkins commented on docs/source/conf.py
> +]
One thing to watch out for is any packages with C-extensions (numpy is a culprit here).  https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules.

In that case you'll probably have to hunt the offending imports down and then place them in something like this:

```python
autodoc_mock_imports = ["pyrap", "s3fs", "xarray"]
```

https://github.com/ratt-ru/dask-ms/blob/53ab607b5ef727d6366b115f8f3060bf61efd603/docs/conf.py#L28

2022-10-24 13:32 UTC, sjperkins requested changes
A poetry docs group will need to be added for RTD to being working, otherwise I've got some low priority suggestions.

I haven't reviewed the Python or cab changes

2022-10-25 13:16 UTC, sphemakh commented
Ready for final review

2022-10-25 13:58 UTC, merged